// Code generated by hostfn-gen; DO NOT EDIT.

package storage

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Storage) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getStorageName", x.W_getStorageName),
		vm.HostFn2("getStorageNameSize", x.W_getStorageNameSize),
	}
}
