// Code generated by hostfn-gen; DO NOT EDIT.

package node

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn1("getNodeId", x.W_getNodeId),
	}
}
