// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package functions

import "github.com/taubyte/tau/pkg/schema/basic"

func Id(value string) basic.Op {
	return basic.Set("id", value)
}

func Description(value string) basic.Op {
	return basic.Set("description", value)
}

func Tags(value []string) basic.Op {
	return basic.Set("tags", value)
}

func Type(value string) basic.Op {
	return basic.SetChild("trigger", "type", value)
}

func Local(value bool) basic.Op {
	return basic.SetChild("trigger", "local", value)
}

func Channel(value string) basic.Op {
	return basic.SetChild("trigger", "channel", value)
}

func Protocol(value string) basic.Op {
	return basic.SetChild("trigger", "protocol", value)
}

// Deprecated: use Protocol.
func Service(value string) basic.Op {
	return basic.SetChild("trigger", "service", value)
}

func Command(value string) basic.Op {
	return basic.SetChild("trigger", "command", value)
}

func Method(value string) basic.Op {
	return basic.SetChild("trigger", "method", value)
}

func Domains(value []string) basic.Op {
	return basic.SetChild("trigger", "domains", value)
}

func Paths(value []string) basic.Op {
	return basic.SetChild("trigger", "paths", value)
}

func Source(value string) basic.Op {
	return basic.Set("source", value)
}

func Timeout(value string) basic.Op {
	return basic.SetChild("execution", "timeout", value)
}

func Memory(value string) basic.Op {
	return basic.SetChild("execution", "memory", value)
}

func Call(value string) basic.Op {
	return basic.SetChild("execution", "call", value)
}

func SmartOps(value []string) basic.Op {
	return basic.Set("smartops", value)
}
