// Code generated by hostfn-gen; DO NOT EDIT.

package memoryView

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostProc1("memoryViewClose", x.W_memoryViewClose),
		vm.HostFn4("memoryViewNew", x.W_memoryViewNew),
		vm.HostFn3("memoryViewOpen", x.W_memoryViewOpen),
		vm.HostFn5("memoryViewRead", x.W_memoryViewRead),
	}
}
