// Code generated by hostfn-gen; DO NOT EDIT.

package website

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Website) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getWebsiteName", x.W_getWebsiteName),
		vm.HostFn2("getWebsiteNameSize", x.W_getWebsiteNameSize),
	}
}
