package vm

type PluginInstance interface {
	// Load will load all Factories to the HostModule, and return the ModuleInstance
	Load(HostModule) (ModuleInstance, error)

	// Close will close the PluginInstance
	Close() error
}

type Factory interface {
	// Close will close and cleanup the Factory
	Close() error

	// Name returns the name of the Factory
	Name() string
}

// HostFunctionProvider is implemented by factories that expose their host
// functions as pre-built, reflection-free definitions (generated by
// hostfn-gen). The plugin loader registers these directly instead of
// discovering W_ methods via reflection.
type HostFunctionProvider interface {
	HostFunctions() []*HostModuleFunctionDefinition
}

// TODO: New takes options for factories
type Plugin interface {
	// New creates a new PluginInstance
	New(Instance) (PluginInstance, error)

	// Name returns the name of the Plugin
	Name() string

	Close() error
}
