// Code generated by hostfn-gen; DO NOT EDIT.

//go:build web3

package ethereum

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn4("ethBlockByNumber", x.W_ethBlockByNumber),
		vm.HostFn3("ethBlockNumberFromId", x.W_ethBlockNumberFromId),
		vm.HostFn3("ethBlockNumberFromIdSize", x.W_ethBlockNumberFromIdSize),
		vm.HostFn5("ethCallContract", x.W_ethCallContract),
		vm.HostFn8("ethCallContractSize", x.W_ethCallContractSize),
		vm.HostFn1("ethCloseClient", x.W_ethCloseClient),
		vm.HostFn2("ethCurrentBlockNumber", x.W_ethCurrentBlockNumber),
		vm.HostFn2("ethCurrentChainId", x.W_ethCurrentChainId),
		vm.HostFn2("ethCurrentChainIdSize", x.W_ethCurrentChainIdSize),
		{
			Name:        "ethDeployContract",
			ParamTypes:  []vm.ValueType{vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32},
			ResultTypes: []vm.ValueType{vm.ValueTypeI32},
			Stack: func(ctx context.Context, m vm.Module, s []uint64) {
				s[0] = uint64(x.W_ethDeployContract(ctx, m, uint32(s[0]), uint32(s[1]), uint32(s[2]), uint32(s[3]), uint32(s[4]), uint32(s[5]), uint32(s[6]), uint32(s[7]), uint32(s[8]), uint32(s[9]), uint32(s[10]), uint32(s[11]), uint32(s[12]), uint32(s[13])))
			},
		},
		vm.HostFn6("ethGetContractMethod", x.W_ethGetContractMethod),
		vm.HostFn6("ethGetContractMethodSize", x.W_ethGetContractMethodSize),
		vm.HostFn4("ethGetTransactionFromBlockByHash", x.W_ethGetTransactionFromBlockByHash),
		vm.HostFn7("ethGetTransactionMethodBytes", x.W_ethGetTransactionMethodBytes),
		vm.HostFn7("ethGetTransactionMethodSize", x.W_ethGetTransactionMethodSize),
		vm.HostFn7("ethGetTransactionMethodUint64", x.W_ethGetTransactionMethodUint64),
		vm.HostFn3("ethGetTransactionsFromBlock", x.W_ethGetTransactionsFromBlock),
		vm.HostFn4("ethGetTransactionsFromBlockSize", x.W_ethGetTransactionsFromBlockSize),
		vm.HostFn3("ethHexToECDSA", x.W_ethHexToECDSA),
		vm.HostFn5("ethJson", x.W_ethJson),
		vm.HostFn5("ethJsonSize", x.W_ethJsonSize),
		vm.HostFn5("ethNew", x.W_ethNew),
		vm.HostFn4("ethNewContract", x.W_ethNewContract),
		vm.HostFn8("ethNewContractSize", x.W_ethNewContractSize),
		vm.HostFn3("ethPubFromPriv", x.W_ethPubFromPriv),
		vm.HostFn5("ethPubKeyFromSignedMessage", x.W_ethPubKeyFromSignedMessage),
		vm.HostFn4("ethSendTransaction", x.W_ethSendTransaction),
		vm.HostFn5("ethSignMessage", x.W_ethSignMessage),
		vm.HostFn7("ethSubscribeContractEvent", x.W_ethSubscribeContractEvent),
		{
			Name:        "ethTransactContract",
			ParamTypes:  []vm.ValueType{vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32, vm.ValueTypeI32},
			ResultTypes: []vm.ValueType{vm.ValueTypeI32},
			Stack: func(ctx context.Context, m vm.Module, s []uint64) {
				s[0] = uint64(x.W_ethTransactContract(ctx, m, uint32(s[0]), uint32(s[1]), uint32(s[2]), uint32(s[3]), uint32(s[4]), uint32(s[5]), uint32(s[6]), uint32(s[7]), uint32(s[8]), uint32(s[9]), uint32(s[10]), uint32(s[11])))
			},
		},
		vm.HostFn7("ethTransactionRawSignatures", x.W_ethTransactionRawSignatures),
		vm.HostFn7("ethTransactionRawSignaturesSize", x.W_ethTransactionRawSignaturesSize),
		vm.HostFn6("ethVerifySignature", x.W_ethVerifySignature),
	}
}
