// Code generated by hostfn-gen; DO NOT EDIT.

package function

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *FunctionP2P) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getFunctionP2PName", x.W_getFunctionP2PName),
		vm.HostFn2("getFunctionP2PNameSize", x.W_getFunctionP2PNameSize),
	}
}
