// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: bcast.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CRDTBroadcast struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heads         []*Head                `protobuf:"bytes,1,rep,name=Heads,proto3" json:"Heads,omitempty"` // A list of heads
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CRDTBroadcast) Reset() {
	*x = CRDTBroadcast{}
	mi := &file_bcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CRDTBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CRDTBroadcast) ProtoMessage() {}

func (x *CRDTBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CRDTBroadcast.ProtoReflect.Descriptor instead.
func (*CRDTBroadcast) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{0}
}

func (x *CRDTBroadcast) GetHeads() []*Head {
	if x != nil {
		return x.Heads
	}
	return nil
}

type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           []byte                 `protobuf:"bytes,1,opt,name=Cid,proto3" json:"Cid,omitempty"`
	DagName       string                 `protobuf:"bytes,2,opt,name=DagName,proto3" json:"DagName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_bcast_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_bcast_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_bcast_proto_rawDescGZIP(), []int{1}
}

func (x *Head) GetCid() []byte {
	if x != nil {
		return x.Cid
	}
	return nil
}

func (x *Head) GetDagName() string {
	if x != nil {
		return x.DagName
	}
	return ""
}

var File_bcast_proto protoreflect.FileDescriptor

const file_bcast_proto_rawDesc = "" +
	"\n" +
	"\vbcast.proto\x12\acrdt.pb\"4\n" +
	"\rCRDTBroadcast\x12#\n" +
	"\x05Heads\x18\x01 \x03(\v2\r.crdt.pb.HeadR\x05Heads\"2\n" +
	"\x04Head\x12\x10\n" +
	"\x03Cid\x18\x01 \x01(\fR\x03Cid\x12\x18\n" +
	"\aDagName\x18\x02 \x01(\tR\aDagNameB\x06Z\x04.;pbb\x06proto3"

var (
	file_bcast_proto_rawDescOnce sync.Once
	file_bcast_proto_rawDescData []byte
)

func file_bcast_proto_rawDescGZIP() []byte {
	file_bcast_proto_rawDescOnce.Do(func() {
		file_bcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bcast_proto_rawDesc), len(file_bcast_proto_rawDesc)))
	})
	return file_bcast_proto_rawDescData
}

var file_bcast_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_bcast_proto_goTypes = []any{
	(*CRDTBroadcast)(nil), // 0: crdt.pb.CRDTBroadcast
	(*Head)(nil),          // 1: crdt.pb.Head
}
var file_bcast_proto_depIdxs = []int32{
	1, // 0: crdt.pb.CRDTBroadcast.Heads:type_name -> crdt.pb.Head
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bcast_proto_init() }
func file_bcast_proto_init() {
	if File_bcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bcast_proto_rawDesc), len(file_bcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bcast_proto_goTypes,
		DependencyIndexes: file_bcast_proto_depIdxs,
		MessageInfos:      file_bcast_proto_msgTypes,
	}.Build()
	File_bcast_proto = out.File
	file_bcast_proto_goTypes = nil
	file_bcast_proto_depIdxs = nil
}
