// Code generated by hostfn-gen; DO NOT EDIT.

package globals

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn5("getGlobalValue", x.W_getGlobalValue),
		vm.HostFn5("getGlobalValueSize", x.W_getGlobalValueSize),
		vm.HostFn5("getOrCreateGlobalValueSize", x.W_getOrCreateGlobalValueSize),
		vm.HostFn7("putGlobalValue", x.W_putGlobalValue),
	}
}
