// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package website

import "github.com/taubyte/tau/pkg/schema/basic"

type getter struct {
	*website
}

func (w *website) Get() Getter {
	return getter{w}
}

func (g getter) Name() string {
	return g.name
}

func (g getter) Application() string {
	return g.application
}

func (g getter) Id() string {
	return basic.Get[string](g, "id")
}

func (g getter) Description() string {
	return basic.Get[string](g, "description")
}

func (g getter) Tags() []string {
	return basic.Get[[]string](g, "tags")
}

func (g getter) Domains() []string {
	return basic.Get[[]string](g, "domains")
}

func (g getter) Paths() []string {
	var v []string
	if g.Config().Get("paths").Value(&v) == nil {
		return v
	}
	return basic.Get[[]string](g, "source", "paths")
}

func (g getter) Branch() string {
	return basic.Get[string](g, "source", "branch")
}

func (g getter) SmartOps() []string {
	return basic.Get[[]string](g, "smartops")
}
