// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package website

import (
	"github.com/taubyte/tau/pkg/schema/basic"
	seer "github.com/taubyte/tau/pkg/yaseer"
)

func Open(seer *seer.Seer, name, application string) (Website, error) {
	website := &website{
		seer:        seer,
		name:        name,
		application: application,
	}

	var err error
	website.Resource, err = basic.New(seer, website, name)
	if err != nil {
		return nil, err
	}

	return website, nil
}
