// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// The struct fields are the mapstructure decode surface; the methods are the
// object-addressing helpers derived from the DSL's Addressing capabilities.

package structureSpec

type Application struct {
	Id          string
	Name        string
	Description string
	Tags        []string
}
