// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Database methods file.

package structureSpec

type Database struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Match       string
	Regex       bool `mapstructure:"useRegex"`
	Local       bool
	Size        uint64
	Key         string
	SmartOps    []string

	Basic
	Indexer
}
