// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Domain methods file.

package structureSpec

type Domain struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Fqdn        string
	CertFile    string `mapstructure:"cert-file"`
	KeyFile     string `mapstructure:"key-file"`
	CertType    string `mapstructure:"cert-type"`
	SmartOps    []string

	Indexer
}
