// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Function methods file.

package structureSpec

type Function struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Type        string
	Local       bool
	Channel     string
	Protocol    string `mapstructure:"service"`
	Command     string
	Method      string
	Domains     []string
	Paths       []string
	Source      string
	Timeout     uint64
	Memory      uint64
	Call        string
	Secure      bool
	SmartOps    []string

	Wasm
}
