// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Messaging methods file.

package structureSpec

type Messaging struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Local       bool
	Match       string
	Regex       bool
	MQTT        bool
	WebSocket   bool
	SmartOps    []string

	Basic
	Wasm
}
