// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// The struct fields are the mapstructure decode surface; the methods are the
// object-addressing helpers derived from the DSL's Addressing capabilities.

package structureSpec

import (
	"github.com/taubyte/tau/pkg/specs/common"
	serviceSpec "github.com/taubyte/tau/pkg/specs/service"
)

type Service struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Protocol    string
	SmartOps    []string

	Indexer
}

func (s Service) GetName() string {
	return s.Name
}

func (s *Service) SetId(id string) {
	s.Id = id
}

func (s *Service) IndexValue(branch, project, app string) (*common.TnsPath, error) {
	return serviceSpec.Tns().IndexValue(branch, project, app, s.Id)
}

func (s *Service) EmptyPath(branch, commit, project, app string) (*common.TnsPath, error) {
	return serviceSpec.Tns().EmptyPath(branch, commit, project, app)
}

func (s *Service) GetId() string {
	return s.Id
}
