// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// The struct fields are the mapstructure decode surface; the methods are the
// object-addressing helpers derived from the DSL's Addressing capabilities.

package structureSpec

import (
	"github.com/taubyte/tau/pkg/specs/common"
	smartopSpec "github.com/taubyte/tau/pkg/specs/smartops"
)

type SmartOp struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Source      string
	Timeout     uint64
	Memory      uint64
	Call        string
	SmartOps    []string

	Wasm
}

func (s SmartOp) GetName() string {
	return s.Name
}

func (s *SmartOp) SetId(id string) {
	s.Id = id
}

func (s *SmartOp) BasicPath(branch, commit, project, app string) (*common.TnsPath, error) {
	return smartopSpec.Tns().BasicPath(branch, commit, project, app, s.Id)
}

func (s *SmartOp) IndexValue(branch, project, app string) (*common.TnsPath, error) {
	return smartopSpec.Tns().IndexValue(branch, project, app, s.Id)
}

func (s *SmartOp) WasmModulePath(project, app string) (*common.TnsPath, error) {
	return smartopSpec.Tns().WasmModulePath(project, app, s.Name)
}

func (s *SmartOp) ModuleName() string {
	return smartopSpec.ModuleName(s.Name)
}

func (s *SmartOp) GetId() string {
	return s.Id
}
