// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// SmartOp methods file.

package structureSpec

type SmartOp struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Source      string
	Timeout     uint64
	Memory      uint64
	Call        string
	SmartOps    []string

	Wasm
}
