// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// The struct fields are the mapstructure decode surface; the methods are the
// object-addressing helpers derived from the DSL's Addressing capabilities.

package structureSpec

import (
	"github.com/taubyte/tau/pkg/specs/common"
	storageSpec "github.com/taubyte/tau/pkg/specs/storage"
)

type Storage struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Type        string
	Match       string
	Regex       bool `mapstructure:"useRegex"`
	Public      bool
	Versioning  bool
	Ttl         uint64
	Size        uint64
	SmartOps    []string

	Basic
	Indexer
}

func (s Storage) GetName() string {
	return s.Name
}

func (s *Storage) SetId(id string) {
	s.Id = id
}

func (s *Storage) BasicPath(branch, commit, project, app string) (*common.TnsPath, error) {
	return storageSpec.Tns().BasicPath(branch, commit, project, app, s.Id)
}

func (s *Storage) IndexValue(branch, project, app string) (*common.TnsPath, error) {
	return storageSpec.Tns().IndexValue(branch, project, app, s.Id)
}

func (s *Storage) IndexPath(project, app string) *common.TnsPath {
	return storageSpec.Tns().IndexPath(project, app, s.Name)
}

func (s *Storage) GetId() string {
	return s.Id
}
