// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Storage methods file.

package structureSpec

type Storage struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Type        string
	Match       string
	Regex       bool `mapstructure:"useRegex"`
	Public      bool
	Versioning  bool
	Ttl         uint64
	Size        uint64
	SmartOps    []string

	Basic
	Indexer
}
