// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// The struct fields are the mapstructure decode surface; the methods are the
// object-addressing helpers derived from the DSL's Addressing capabilities.

package structureSpec

import (
	"github.com/taubyte/tau/pkg/specs/common"
	websiteSpec "github.com/taubyte/tau/pkg/specs/website"
)

type Website struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Domains     []string
	Paths       []string
	Branch      string
	Provider    string
	RepoID      string `mapstructure:"repository-id"`
	RepoName    string `mapstructure:"repository-name"`
	SmartOps    []string

	Basic
	Wasm
}

func (w Website) GetName() string {
	return w.Name
}

func (w *Website) SetId(id string) {
	w.Id = id
}

func (w *Website) BasicPath(branch, commit, project, app string) (*common.TnsPath, error) {
	return websiteSpec.Tns().BasicPath(branch, commit, project, app, w.Id)
}

func (w *Website) IndexValue(branch, project, app string) (*common.TnsPath, error) {
	return websiteSpec.Tns().IndexValue(branch, project, app, w.Id)
}

func (w *Website) HttpPath(fqdn string) (*common.TnsPath, error) {
	return websiteSpec.Tns().HttpPath(fqdn)
}

func (w *Website) WasmModulePath(project, app string) (*common.TnsPath, error) {
	return websiteSpec.Tns().WasmModulePath(project, app, w.Name)
}

func (w *Website) ModuleName() string {
	return websiteSpec.ModuleName(w.Name)
}

func (w *Website) GetId() string {
	return w.Id
}
