// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go
//
// Struct type only (the mapstructure decode surface). The object-addressing
// methods (GetName/SetId/BasicPath/...) are hand-written in the sibling
// Website methods file.

package structureSpec

type Website struct {
	Id          string
	Name        string
	Description string
	Tags        []string
	Domains     []string
	Paths       []string
	Branch      string
	Provider    string
	RepoID      string `mapstructure:"repository-id"`
	RepoName    string `mapstructure:"repository-name"`
	SmartOps    []string

	Basic
	Wasm
}
