# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drive/v1/drive.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drive/v1/drive.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ...config.v1 import config_pb2 as config_dot_v1_dot_config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64rive/v1/drive.proto\x12\x08\x64rive.v1\x1a\x16\x63onfig/v1/config.proto\"\xa0\x01\n\x0c\x44riveRequest\x12)\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x11.config.v1.ConfigR\x06\x63onfig\x12\x18\n\x06latest\x18\x02 \x01(\x08H\x00R\x06latest\x12\x1a\n\x07version\x18\x03 \x01(\tH\x00R\x07version\x12\x12\n\x03url\x18\x04 \x01(\tH\x00R\x03url\x12\x14\n\x04path\x18\x05 \x01(\tH\x00R\x04pathB\x05\n\x03tau\"n\n\x0bPlotRequest\x12%\n\x05\x64rive\x18\x01 \x01(\x0b\x32\x0f.drive.v1.DriveR\x05\x64rive\x12\x16\n\x06shapes\x18\x02 \x03(\tR\x06shapes\x12 \n\x0b\x63oncurrency\x18\x03 \x01(\x05R\x0b\x63oncurrency\"\x17\n\x05\x44rive\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"\x18\n\x06\x43ourse\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\"p\n\x14\x44isplacementProgress\x12\x12\n\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n\x08progress\x18\x03 \x01(\x05R\x08progress\x12\x14\n\x05\x65rror\x18\x04 \x01(\tR\x05\x65rror\"\x07\n\x05\x45mpty2\xb4\x02\n\x0c\x44riveService\x12.\n\x03New\x12\x16.drive.v1.DriveRequest\x1a\x0f.drive.v1.Drive\x12/\n\x04Plot\x12\x15.drive.v1.PlotRequest\x1a\x10.drive.v1.Course\x12-\n\x08\x44isplace\x12\x10.drive.v1.Course\x1a\x0f.drive.v1.Empty\x12>\n\x08Progress\x12\x10.drive.v1.Course\x1a\x1e.drive.v1.DisplacementProgress0\x01\x12*\n\x05\x41\x62ort\x12\x10.drive.v1.Course\x1a\x0f.drive.v1.Empty\x12(\n\x04\x46ree\x12\x0f.drive.v1.Drive\x1a\x0f.drive.v1.EmptyB\x9e\x01\n\x0c\x63om.drive.v1B\nDriveProtoP\x01ZAgithub.com/taubyte/tau/pkg/spore-drive/proto/gen/drive/v1;drivev1\xa2\x02\x03\x44XX\xaa\x02\x08\x44rive.V1\xca\x02\x08\x44rive\\V1\xe2\x02\x14\x44rive\\V1\\GPBMetadata\xea\x02\tDrive::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drive.v1.drive_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.drive.v1B\nDriveProtoP\001ZAgithub.com/taubyte/tau/pkg/spore-drive/proto/gen/drive/v1;drivev1\242\002\003DXX\252\002\010Drive.V1\312\002\010Drive\\V1\342\002\024Drive\\V1\\GPBMetadata\352\002\tDrive::V1'
  _globals['_DRIVEREQUEST']._serialized_start=59
  _globals['_DRIVEREQUEST']._serialized_end=219
  _globals['_PLOTREQUEST']._serialized_start=221
  _globals['_PLOTREQUEST']._serialized_end=331
  _globals['_DRIVE']._serialized_start=333
  _globals['_DRIVE']._serialized_end=356
  _globals['_COURSE']._serialized_start=358
  _globals['_COURSE']._serialized_end=382
  _globals['_DISPLACEMENTPROGRESS']._serialized_start=384
  _globals['_DISPLACEMENTPROGRESS']._serialized_end=496
  _globals['_EMPTY']._serialized_start=498
  _globals['_EMPTY']._serialized_end=505
  _globals['_DRIVESERVICE']._serialized_start=508
  _globals['_DRIVESERVICE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
