// Code generated by hostfn-gen; DO NOT EDIT.

package database

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Database) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getDatabaseName", x.W_getDatabaseName),
		vm.HostFn2("getDatabaseNameSize", x.W_getDatabaseNameSize),
	}
}
