// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package domains

import "github.com/taubyte/tau/pkg/schema/basic"

type getter struct {
	*domain
}

func (d *domain) Get() Getter {
	return getter{d}
}

func (g getter) Name() string {
	return g.name
}

func (g getter) Application() string {
	return g.application
}

func (g getter) Id() string {
	return basic.Get[string](g, "id")
}

func (g getter) Description() string {
	return basic.Get[string](g, "description")
}

func (g getter) Tags() []string {
	return basic.Get[[]string](g, "tags")
}

func (g getter) Cert() string {
	return basic.Get[string](g, "certificate", "cert")
}

func (g getter) Key() string {
	return basic.Get[string](g, "certificate", "key")
}

func (g getter) Type() string {
	return basic.Get[string](g, "certificate", "type")
}

func (g getter) SmartOps() []string {
	return basic.Get[[]string](g, "smartops")
}
