// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package domains

import "github.com/taubyte/tau/pkg/schema/basic"

func Id(value string) basic.Op {
	return basic.Set("id", value)
}

func Description(value string) basic.Op {
	return basic.Set("description", value)
}

func Tags(value []string) basic.Op {
	return basic.Set("tags", value)
}

func FQDN(value string) basic.Op {
	return basic.Set("fqdn", value)
}

func Cert(value string) basic.Op {
	return basic.SetChild("certificate", "cert", value)
}

func Key(value string) basic.Op {
	return basic.SetChild("certificate", "key", value)
}

func Type(value string) basic.Op {
	return basic.SetChild("certificate", "type", value)
}

func SmartOps(value []string) basic.Op {
	return basic.Set("smartops", value)
}
