// Code generated by hostfn-gen; DO NOT EDIT.

package storage

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn1("contentCloseFile", x.W_contentCloseFile),
		vm.HostFn2("contentFileCid", x.W_contentFileCid),
		vm.HostFn2("contentPushFile", x.W_contentPushFile),
		vm.HostFn4("contentReadFile", x.W_contentReadFile),
		vm.HostFn4("contentSeekFile", x.W_contentSeekFile),
		vm.HostFn4("contentWriteFile", x.W_contentWriteFile),
		vm.HostFn7("storageAddFile", x.W_storageAddFile),
		vm.HostFn2("storageCapacity", x.W_storageCapacity),
		vm.HostFn2("storageCapacitySize", x.W_storageCapacitySize),
		vm.HostFn4("storageCid", x.W_storageCid),
		vm.HostFn2("storageCloseFile", x.W_storageCloseFile),
		vm.HostFn3("storageCurrentVersion", x.W_storageCurrentVersion),
		vm.HostFn4("storageCurrentVersionSize", x.W_storageCurrentVersionSize),
		vm.HostFn5("storageDeleteFile", x.W_storageDeleteFile),
		vm.HostFn3("storageGet", x.W_storageGet),
		vm.HostFn5("storageGetFile", x.W_storageGetFile),
		vm.HostFn2("storageListFiles", x.W_storageListFiles),
		vm.HostFn2("storageListFilesSize", x.W_storageListFilesSize),
		vm.HostFn4("storageListVersions", x.W_storageListVersions),
		vm.HostFn4("storageListVersionsSize", x.W_storageListVersionsSize),
		vm.HostFn3("storageNew", x.W_storageNew),
		vm.HostFn1("storageNewContent", x.W_storageNewContent),
		vm.HostFn2("storageOpenCid", x.W_storageOpenCid),
		vm.HostFn5("storageReadFile", x.W_storageReadFile),
		vm.HostFn2("storageUsed", x.W_storageUsed),
		vm.HostFn2("storageUsedSize", x.W_storageUsedSize),
	}
}
