release:
  # Repo in which the release will be created.
  github:
    owner: taubyte
    name: tau

  # Control the draft and prerelease settings
  draft: false
  replace_existing_draft: false
  prerelease: auto

  # Release naming and SCM interaction
  name_template: ""
  disable: false
  skip_upload: false
  
builds:
  - id: "windows"
    main: "./tools/dream/main.go"
    binary: "dream"
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
      - GOAMD64=v2
    tags:
      - windows

changelog:
  disable: true

checksum:
  disable: true

archives:
  - files:
    - none*
