// Code generated by hostfn-gen; DO NOT EDIT.

package client

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn6("addHttpRequestHeader", x.W_addHttpRequestHeader),
		vm.HostFn2("closeHttpResponseBody", x.W_closeHttpResponseBody),
		vm.HostFn4("deleteHttpRequestHeader", x.W_deleteHttpRequestHeader),
		vm.HostFn2("doHttpRequest", x.W_doHttpRequest),
		vm.HostFn5("getHttpRequestHeader", x.W_getHttpRequestHeader),
		vm.HostFn4("getHttpRequestHeaderKeys", x.W_getHttpRequestHeaderKeys),
		vm.HostFn3("getHttpRequestHeaderKeysSize", x.W_getHttpRequestHeaderKeysSize),
		vm.HostFn5("getHttpRequestHeaderSize", x.W_getHttpRequestHeaderSize),
		vm.HostFn3("getHttpRequestMethod", x.W_getHttpRequestMethod),
		vm.HostFn5("getHttpResponseHeader", x.W_getHttpResponseHeader),
		vm.HostFn4("getHttpResponseHeaderKeys", x.W_getHttpResponseHeaderKeys),
		vm.HostFn3("getHttpResponseHeaderKeysSize", x.W_getHttpResponseHeaderKeysSize),
		vm.HostFn5("getHttpResponseHeaderSize", x.W_getHttpResponseHeaderSize),
		vm.HostFn1("newHttpClient", x.W_newHttpClient),
		vm.HostFn2("newHttpRequest", x.W_newHttpRequest),
		vm.HostFn5("readHttpResponseBody", x.W_readHttpResponseBody),
		vm.HostFn4("setHttpRequestBody", x.W_setHttpRequestBody),
		vm.HostFn6("setHttpRequestHeader", x.W_setHttpRequestHeader),
		vm.HostFn3("setHttpRequestMethod", x.W_setHttpRequestMethod),
		vm.HostFn4("setHttpRequestURL", x.W_setHttpRequestURL),
	}
}
