// Code generated by hostfn-gen; DO NOT EDIT.

package self

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn1("selfApplication", x.W_selfApplication),
		vm.HostFn1("selfApplicationSize", x.W_selfApplicationSize),
		vm.HostFn1("selfBranches", x.W_selfBranches),
		vm.HostFn1("selfBranchesSize", x.W_selfBranchesSize),
		vm.HostFn1("selfCommit", x.W_selfCommit),
		vm.HostFn1("selfCommitSize", x.W_selfCommitSize),
		vm.HostFn1("selfId", x.W_selfId),
		vm.HostFn1("selfIdSize", x.W_selfIdSize),
		vm.HostFn1("selfProject", x.W_selfProject),
		vm.HostFn1("selfProjectSize", x.W_selfProjectSize),
	}
}
