// Code generated by hostfn-gen; DO NOT EDIT.

//go:build web3

package client

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("ipfsCloseFile", x.W_ipfsCloseFile),
		vm.HostFn3("ipfsFileCid", x.W_ipfsFileCid),
		vm.HostFn2("ipfsNewContent", x.W_ipfsNewContent),
		vm.HostFn3("ipfsOpenFile", x.W_ipfsOpenFile),
		vm.HostFn3("ipfsPushFile", x.W_ipfsPushFile),
		vm.HostFn5("ipfsReadFile", x.W_ipfsReadFile),
		vm.HostFn5("ipfsSeekFile", x.W_ipfsSeekFile),
		vm.HostFn5("ipfsWriteFile", x.W_ipfsWriteFile),
		vm.HostFn1("newIpfsClient", x.W_newIpfsClient),
	}
}
