# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: health/v1/health.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16health/v1/health.proto\x12\thealth.v1\"+\n\x0fSupportsRequest\x12\x18\n\x07version\x18\x01 \x01(\tR\x07version\"\x07\n\x05\x45mpty2u\n\rHealthService\x12*\n\x04Ping\x12\x10.health.v1.Empty\x1a\x10.health.v1.Empty\x12\x38\n\x08Supports\x12\x1a.health.v1.SupportsRequest\x1a\x10.health.v1.EmptyB\xa6\x01\n\rcom.health.v1B\x0bHealthProtoP\x01ZCgithub.com/taubyte/tau/pkg/spore-drive/proto/gen/health/v1;healthv1\xa2\x02\x03HXX\xaa\x02\tHealth.V1\xca\x02\tHealth\\V1\xe2\x02\x15Health\\V1\\GPBMetadata\xea\x02\nHealth::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.health.v1B\013HealthProtoP\001ZCgithub.com/taubyte/tau/pkg/spore-drive/proto/gen/health/v1;healthv1\242\002\003HXX\252\002\tHealth.V1\312\002\tHealth\\V1\342\002\025Health\\V1\\GPBMetadata\352\002\nHealth::V1'
  _globals['_SUPPORTSREQUEST']._serialized_start=37
  _globals['_SUPPORTSREQUEST']._serialized_end=80
  _globals['_EMPTY']._serialized_start=82
  _globals['_EMPTY']._serialized_end=89
  _globals['_HEALTHSERVICE']._serialized_start=91
  _globals['_HEALTHSERVICE']._serialized_end=208
# @@protoc_insertion_point(module_scope)
