// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package libraries

import "github.com/taubyte/tau/pkg/schema/basic"

type getter struct {
	*library
}

func (l *library) Get() Getter {
	return getter{l}
}

func (g getter) Name() string {
	return g.name
}

func (g getter) Application() string {
	return g.application
}

func (g getter) Id() string {
	return basic.Get[string](g, "id")
}

func (g getter) Description() string {
	return basic.Get[string](g, "description")
}

func (g getter) Tags() []string {
	return basic.Get[[]string](g, "tags")
}

func (g getter) Path() string {
	return basic.Get[string](g, "source", "path")
}

func (g getter) Branch() string {
	return basic.Get[string](g, "source", "branch")
}

func (g getter) SmartOps() []string {
	return basic.Get[[]string](g, "smartops")
}
