// Code generated by hostfn-gen; DO NOT EDIT.

package function

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *FunctionPubSub) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getFunctionPubSubName", x.W_getFunctionPubSubName),
		vm.HostFn2("getFunctionPubSubNameSize", x.W_getFunctionPubSubNameSize),
	}
}
