// Code generated by hostfn-gen; DO NOT EDIT.

package event

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn1("closeHttpEventBody", x.W_closeHttpEventBody),
		vm.HostFn1("eventHttpFlush", x.W_eventHttpFlush),
		vm.HostFn5("eventHttpHeaderAdd", x.W_eventHttpHeaderAdd),
		vm.HostFn4("eventHttpRedirect", x.W_eventHttpRedirect),
		vm.HostFn2("eventHttpRetCode", x.W_eventHttpRetCode),
		vm.HostFn4("eventHttpWrite", x.W_eventHttpWrite),
		vm.HostProc2("getEventType", x.W_getEventType),
		vm.HostFn5("getHttpEventHeaders", x.W_getHttpEventHeaders),
		vm.HostFn4("getHttpEventHeadersSize", x.W_getHttpEventHeadersSize),
		vm.HostFn3("getHttpEventHost", x.W_getHttpEventHost),
		vm.HostFn2("getHttpEventHostSize", x.W_getHttpEventHostSize),
		vm.HostFn3("getHttpEventMethod", x.W_getHttpEventMethod),
		vm.HostFn2("getHttpEventMethodSize", x.W_getHttpEventMethodSize),
		vm.HostFn3("getHttpEventPath", x.W_getHttpEventPath),
		vm.HostFn2("getHttpEventPathSize", x.W_getHttpEventPathSize),
		vm.HostFn5("getHttpEventQueryValueByName", x.W_getHttpEventQueryValueByName),
		vm.HostFn4("getHttpEventQueryValueByNameSize", x.W_getHttpEventQueryValueByNameSize),
		vm.HostFn3("getHttpEventRequestHeaderKeys", x.W_getHttpEventRequestHeaderKeys),
		vm.HostFn2("getHttpEventRequestHeaderKeysSize", x.W_getHttpEventRequestHeaderKeysSize),
		vm.HostFn2("getHttpEventRequestQueryKeys", x.W_getHttpEventRequestQueryKeys),
		vm.HostFn2("getHttpEventRequestQueryKeysSize", x.W_getHttpEventRequestQueryKeysSize),
		vm.HostFn3("getHttpEventUserAgent", x.W_getHttpEventUserAgent),
		vm.HostFn2("getHttpEventUserAgentSize", x.W_getHttpEventUserAgentSize),
		vm.HostFn2("getMessageChannel", x.W_getMessageChannel),
		vm.HostFn2("getMessageChannelSize", x.W_getMessageChannelSize),
		vm.HostFn2("getMessageData", x.W_getMessageData),
		vm.HostFn2("getMessageDataSize", x.W_getMessageDataSize),
		vm.HostFn2("getP2PEventCommand", x.W_getP2PEventCommand),
		vm.HostFn2("getP2PEventCommandSize", x.W_getP2PEventCommandSize),
		vm.HostFn2("getP2PEventData", x.W_getP2PEventData),
		vm.HostFn2("getP2PEventDataSize", x.W_getP2PEventDataSize),
		vm.HostFn2("getP2PEventFrom", x.W_getP2PEventFrom),
		vm.HostFn2("getP2PEventProtocol", x.W_getP2PEventProtocol),
		vm.HostFn2("getP2PEventProtocolSize", x.W_getP2PEventProtocolSize),
		vm.HostFn2("getP2PEventTo", x.W_getP2PEventTo),
		vm.HostFn4("readHttpEventBody", x.W_readHttpEventBody),
		vm.HostFn3("writeP2PResponse", x.W_writeP2PResponse),
	}
}
