// Code generated by hostfn-gen; DO NOT EDIT.

package service

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Service) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getServiceName", x.W_getServiceName),
		vm.HostFn2("getServiceNameSize", x.W_getServiceNameSize),
	}
}
