// Code generated by hostfn-gen; DO NOT EDIT.

package p2p

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("discoverPeers", x.W_discoverPeers),
		vm.HostFn4("discoverPeersSize", x.W_discoverPeersSize),
		vm.HostFn4("listenToProtocol", x.W_listenToProtocol),
		vm.HostFn3("listenToProtocolSize", x.W_listenToProtocolSize),
		vm.HostFn5("newCommand", x.W_newCommand),
		vm.HostFn3("readCommandResponse", x.W_readCommandResponse),
		vm.HostFn4("sendCommand", x.W_sendCommand),
		vm.HostFn5("sendCommandTo", x.W_sendCommandTo),
	}
}
