// Code generated by hostfn-gen; DO NOT EDIT.

package resource

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	defs := []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getEventId", x.W_getEventId),
		vm.HostFn2("getResourceType", x.W_getResourceType),
	}
	defs = append(defs, x.Database.HostFunctions()...)
	defs = append(defs, x.FunctionHttp.HostFunctions()...)
	defs = append(defs, x.FunctionP2P.HostFunctions()...)
	defs = append(defs, x.FunctionPubSub.HostFunctions()...)
	defs = append(defs, x.MessagingPubSub.HostFunctions()...)
	defs = append(defs, x.MessagingWebSocket.HostFunctions()...)
	defs = append(defs, x.Service.HostFunctions()...)
	defs = append(defs, x.Storage.HostFunctions()...)
	defs = append(defs, x.Website.HostFunctions()...)
	return defs
}
