// Code generated by hostfn-gen; DO NOT EDIT.

package client

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn1("databaseClose", x.W_databaseClose),
		vm.HostFn3("databaseDelete", x.W_databaseDelete),
		vm.HostFn4("databaseGet", x.W_databaseGet),
		vm.HostFn4("databaseGetSize", x.W_databaseGetSize),
		vm.HostFn4("databaseList", x.W_databaseList),
		vm.HostFn4("databaseListSize", x.W_databaseListSize),
		vm.HostFn5("databasePut", x.W_databasePut),
		vm.HostFn3("newDatabase", x.W_newDatabase),
	}
}
