// Code generated by hostfn-gen; DO NOT EDIT.

package dns

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn4("dnsLookupAddress", x.W_dnsLookupAddress),
		vm.HostFn4("dnsLookupAddressSize", x.W_dnsLookupAddressSize),
		vm.HostFn4("dnsLookupCNAME", x.W_dnsLookupCNAME),
		vm.HostFn4("dnsLookupCNAMESize", x.W_dnsLookupCNAMESize),
		vm.HostFn4("dnsLookupMX", x.W_dnsLookupMX),
		vm.HostFn4("dnsLookupMXSize", x.W_dnsLookupMXSize),
		vm.HostFn4("dnsLookupTxT", x.W_dnsLookupTxT),
		vm.HostFn4("dnsLookupTxTSize", x.W_dnsLookupTxTSize),
		vm.HostFn1("dnsNewResolver", x.W_dnsNewResolver),
		vm.HostFn5("dnsRerouteResolver", x.W_dnsRerouteResolver),
		vm.HostFn1("dnsResetResolver", x.W_dnsResetResolver),
	}
}
