// Code generated by hostfn-gen; DO NOT EDIT.

package function

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *FunctionHttp) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn2("getFunctionHttpName", x.W_getFunctionHttpName),
		vm.HostFn2("getFunctionHttpNameSize", x.W_getFunctionHttpNameSize),
	}
}
