// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package storages

import "github.com/taubyte/tau/pkg/schema/basic"

type getter struct {
	*storage
}

func (s *storage) Get() Getter {
	return getter{s}
}

func (g getter) Name() string {
	return g.name
}

func (g getter) Application() string {
	return g.application
}

func (g getter) Id() string {
	return basic.Get[string](g, "id")
}

func (g getter) Description() string {
	return basic.Get[string](g, "description")
}

func (g getter) Tags() []string {
	return basic.Get[[]string](g, "tags")
}

func (g getter) Match() string {
	return basic.Get[string](g, "match")
}

func (g getter) Regex() bool {
	var v bool
	if g.Config().Get("regex").Value(&v) == nil {
		return v
	}
	return basic.Get[bool](g, "useRegex")
}

// Deprecated: use Regex.
func (g getter) UseRegex() bool {
	return basic.Get[bool](g, "useRegex")
}

func (g getter) Versioning() bool {
	return basic.Get[bool](g, "object", "versioning")
}

func (g getter) TTL() string {
	return basic.Get[string](g, "streaming", "ttl")
}

func (g getter) SmartOps() []string {
	return basic.Get[[]string](g, "smartops")
}
