// Code generated by tcc-gen; DO NOT EDIT.
// Source: pkg/tcc/taubyte/v1/schema/definition.go

package storages

import "github.com/taubyte/tau/pkg/schema/basic"

func Id(value string) basic.Op {
	return basic.Set("id", value)
}

func Description(value string) basic.Op {
	return basic.Set("description", value)
}

func Tags(value []string) basic.Op {
	return basic.Set("tags", value)
}

func Match(value string) basic.Op {
	return basic.Set("match", value)
}

func Regex(value bool) basic.Op {
	return basic.Set("regex", value)
}

// Deprecated: use Regex.
func UseRegex(value bool) basic.Op {
	return basic.Set("useRegex", value)
}

func SmartOps(value []string) basic.Op {
	return basic.Set("smartops", value)
}
