// Code generated by hostfn-gen; DO NOT EDIT.

package rand

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn3("cryptoRead", x.W_cryptoRead),
	}
}
