// Code generated by hostfn-gen; DO NOT EDIT.

package pubsub

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostFn3("getWebSocketURL", x.W_getWebSocketURL),
		vm.HostFn3("getWebSocketURLSize", x.W_getWebSocketURLSize),
		vm.HostFn4("publishToChannel", x.W_publishToChannel),
		vm.HostFn2("setSubscriptionChannel", x.W_setSubscriptionChannel),
	}
}
