// Code generated by hostfn-gen; DO NOT EDIT.

package fifo

import (
	"context"

	"github.com/taubyte/tau/core/vm"
)

var _ = context.Background // keep context imported even if unused

func (x *Factory) HostFunctions() []*vm.HostModuleFunctionDefinition {
	return []*vm.HostModuleFunctionDefinition{
		vm.HostProc1("fifoClose", x.W_fifoClose),
		vm.HostFn2("fifoIsCloser", x.W_fifoIsCloser),
		vm.HostFn1("fifoNew", x.W_fifoNew),
		vm.HostFn2("fifoPop", x.W_fifoPop),
		vm.HostFn2("fifoPush", x.W_fifoPush),
	}
}
